name: "run local"
on:
  issues:
    types: [closed, reopened]
  pull_request:
    types: [closed, reopened]

jobs:
  # unit tests
  run-local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
